### PR TITLE
Remove home/download page and set webtools as new home

### PR DESCRIPTION
**Pull request by tokland**
[19-scipion-refactor]

- The old home has been removed and /webtools is the new home. 
- All code related to the download form has been removed.

Note that our EyeSeeTea/scipion-web/development currently has an up-to-date EyeSeeTea/scipion-web/web-develop (which, in turn, is synced to its web-master)

http://dev.eyeseetea.com:8000/

cnb1

Note that some actions are now working in the DEV server because we don't have the complete files of production. For example: 
http://dev.eyeseetea.com:8000/mymovies -> Explore -> "S.cereviseae 80S ribosome" -> Go To Project
redirects to http://dev.eyeseetea.com:8000/m_content?p=80SRiboTestData, which results in a server Error (500): Exception: Cannot load project, path doesn't exist: /home/ec2-user/ScipionUserData/movies/projects/80SRiboTestData.

### CODE REVIEW

**Comment by adrianq** [comment]
@tokland This need to be merged with web-develop from i2pc as discussed right?

**Comment by tokland** [comment]
Both development and the pr branch already use web-develop as base, do you see anything wrong?

**Comment by adrianq** [comment]
screenshot from 2017-06-29 14 35 13

being upstream https://github.com/I2PC/scipion-web

**Comment by tokland** [comment]
Sorry, you are right! I pushed the merge in development but not to the branch. Done and uploaded to DEV, everything's ok: http://dev.eyeseetea.com:8000/

**Pull request merged**
